FROM docker.elastic.co/wolfi/jdk:openjdk-25.0.3-r6-dev@sha256:72cdebdd4f35c880568894eef0c4a14773e885abec414dc62a57ace74419fa25

USER root

WORKDIR /app

COPY . .

ENV GRADLE_OPTS="-Xmx512m -XX:MaxMetaspaceSize=256m"

CMD ["./gradlew", "test", "e2eTest", "--no-daemon", "--info", "--stacktrace"]
